baseURL = "https://gitblog.xiaoyaozone.com/"
defaultContentLanguage = "zh-cn"
title = "逍遥域"
theme = "blowfish"
enableRobotsTXT = true
enableEmoji = true
summaryLength = 0
hasCJKLanguage = true

[pagination]
  pagerSize = 8

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 80

  [[related.indices]]
    name = "date"
    weight = 10
